/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Ruangan;

/**
 *
 * @author Asus A450CA
 */
public class DaftarRuangan extends javax.swing.JFrame {

    /**
     * Creates new form DaftarRuangan
     */
    public DaftarRuangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnPasien = new javax.swing.JMenuItem();
        mnDokter = new javax.swing.JMenuItem();
        mnRuangan = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelRuangan = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        btnHapusRuangan = new javax.swing.JButton();
        btnTambahRuangan = new javax.swing.JButton();

        mnPasien.setText("jMenuItem1");
        jPopupMenu1.add(mnPasien);

        mnDokter.setText("jMenuItem2");
        jPopupMenu1.add(mnDokter);

        mnRuangan.setText("jMenuItem3");
        jPopupMenu1.add(mnRuangan);

        setTitle("Ruangan");

        tabelRuangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Jumlah Pasien", "Kapasitas", "Status"
            }
        ));
        jScrollPane1.setViewportView(tabelRuangan);

        btnHapusRuangan.setText("Hapus Ruangan");

        btnTambahRuangan.setText("Tambah Ruangan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHapusRuangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTambahRuangan)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHapusRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(btnTambahRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusRuangan;
    private javax.swing.JButton btnTambahRuangan;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnDokter;
    private javax.swing.JMenuItem mnPasien;
    private javax.swing.JMenuItem mnRuangan;
    private javax.swing.JTable tabelRuangan;
    // End of variables declaration//GEN-END:variables
    
    public JMenuItem getMnDokter() {
        return mnDokter;
    }
    
     public void setMnDokter() {
      this.mnDokter.setText("Daftar Dokter");
    }

    public JMenuItem getMnPasien() {
        return mnPasien;
    }

    public void setMnPasien() {
        this.mnPasien.setText("Daftar Pasien");
    }

    public JMenuItem getMnRuangan() {
        return mnRuangan;
    }

    public void setMnRuangan() {
        this.mnRuangan.setText("Daftar Ruangan");
    }
    
    public void addListener(ActionListener e){
        btnHapusRuangan.addActionListener(e);
        btnTambahRuangan.addActionListener(e);
        mnPasien.addActionListener(e);
        mnDokter.addActionListener(e);
        mnRuangan.addActionListener(e);
    }

    public JButton getBtnHapusRuangan() {
        return btnHapusRuangan;
    }

    public JButton getBtnTambahRuangan() {
        return btnTambahRuangan;
    }

    public JTable getTabelRuangan() {
        return tabelRuangan;
    }
    
     public int getSelectedDokter(){
        return tabelRuangan.getSelectedRow();
    }
     
    public void addAdapter(MouseAdapter me){
        tabelRuangan.addMouseListener(me);
    }

    public JPopupMenu getjPopupMenu1() {
        return jPopupMenu1;
    }
    
    
    //====================================================================
    public void viewRuangan(ArrayList<Ruangan> listRuangan){
         String[] title = {
            "no Ruangan", "Jumlah Pasien Inap", "Kapasitas", "Status"
        };
        String[][] data = new String[listRuangan.size()][4];
        for (int i = 0; i < listRuangan.size(); i++){
            Ruangan r = listRuangan.get(i);           
                data[i][0] = String.valueOf(r.getNo());
                data[i][1] = String.valueOf( r.getJumlahPasien());
                data[i][2] = String.valueOf( r.getMaxPasien());
                data[i][3] = r.getKetersediaan();
                
            
        }
        tabelRuangan.setModel(new DefaultTableModel(data, title));
    }

}
